### ISSUE TITLE
Invalid tiff file - not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Starahoush** [labsyspharm/minerva-author#51]
I downloaded some ome.tiff files from [nanostring ](https://nanostring.com/products/geomx-digital-spatial-profiler/spatial-organ-atlas/human-lymph-node/) but cannot open them using minerva, which is odd given that there is a minerva story on the website using the same files. I am not sure how to get the full error log but with you can guide me, I will reply as soon as possible.

Here is the issue on the browser:
![browser](https://user-images.githubusercontent.com/67844695/196298848-0b5b906b-24ff-49c0-88c0-e5f04df30814.jpeg)

And here the message on the prompt:
![prompt](https://user-images.githubusercontent.com/67844695/196298863-0edcbf09-939d-4d2f-aab2-b1f59bda3b23.jpeg)

I tried multiple times, that's why there are many occurences. I am currently using windows 10. Tried running on Chrome and Opera GX.

Not sure if this is helpful but the console says regarding the import tiff file issue:
value @ bundle.3652200fbef473bea6f2.js:280
![console](https://user-images.githubusercontent.com/67844695/196299047-be35b3ae-26c6-4f3d-b98b-dc5ea8e65c36.jpeg)

Thank you in advance,
Igor

**Comment by thejohnhoffer** [comment]
I am currently downloading the relevant Nanostring gzip archive. When I have a solution, I will resolve this issue as well as issue #43, where this error was first recognized in a comment. Thanks for creating a separate issue for this specific problem.

**Comment by thejohnhoffer** [comment]
The latest version of [Minerva Author v1.11.1](https://github.com/labsyspharm/minerva-author/releases/tag/v1.11.1) resolves this issue when tested on Windows 11. The issue was  caused by outdated dependencies in the generated Windows executable for v1.10.
