### ISSUE TITLE
Unable to open RGB ome-tiff

### ISSUE THREAD

**Issue by Yu-AnChen** [labsyspharm/minerva-author#66]
Hey I'm experiencing issues when opening RGB image in Minerva Author (v1.15.1, Windows version). There are [3 tiny testing images here](https://github.com/labsyspharm/minerva-author/files/12571031/rgb-issue.zip). The only file I was able to load into minerva author is `HE-minisblack.ome.tif`, which is actually not in a proper RGB format. The `rgb-merge-HE-minisblack.ome.tif` was generated with the script [here](https://github.com/jmuhlich/ome-tiff-pyramid-tools/blob/a5ba0d440bfdd51db01e79ed7c3f58c62c22df33/rgb_merge.py). And the `HE-rgb.ome.tif`'s pixel data is identical to `HE-minisblack.ome.tif`, but with tiff tag `PlanarConfiguration=SEPARATE` and `PhotometricInterpretation=RGB`

**Comment by thejohnhoffer** [comment]
Hi @Yu-AnChen. This issue has just been resolve in tag v1.16.1.
