### ISSUE TITLE
Initial view does not match what is shown in edit mode by default

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/minerva-author#75]
## Steps to reproduce
1. Create new story
2. Immediately click Preview
3. Observe that image framing is not the same as what was shown in edit mode
## Expected behavior
Framing of initial view matches default view (whole image).

**Comment by thejohnhoffer** [comment]
Resolved in [v1.18.2](https://github.com/labsyspharm/minerva-author/releases/tag/v1.18.2)
